# This is a basic workflow to help you get started with Actions

name: Action Practice

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Output a message
        run: echo "Action Complete!"
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Start workflow message
        run: echo "Now running build workflow."

      # Runs a set of commands using the runners shell
      - name: Ending workflow message
        run: |
          echo "Now ending build workflow."
          echo "Have a great day!"
